CREATE DATABASE PetShopDB
GO

USE PetShopDB
GO

CREATE TABLE Customers(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FirstName NVARCHAR(250) NOT NULL,
    LastName NVARCHAR(250) NOT NULL,
    Address NVARCHAR(250) NOT NULL,
    PostalCode INT NOT NULL,
    City NVARCHAR(250) NOT NULL,
    Email NVARCHAR(250) NOT NULL
)
GO

CREATE TABLE Orders(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CustomerID INT NOT NULL,
    Total FLOAT NOT NULL,
    OrderDate DATETIME2 NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customers(ID) ON DELETE CASCADE
)
GO

CREATE TABLE Products (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(250) NOT NULL,
    Category NVARCHAR(250) NOT NULL,
    Price DECIMAL(18,2) NOT NULL
)
GO

CREATE TABLE ProductOrders (
    ProductID INT NOT NULL,
    OrderID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (ProductID) REFERENCES Products(ID) ON DELETE CASCADE,
    FOREIGN KEY (OrderID) REFERENCES Orders(ID) ON DELETE CASCADE
)
GO
